### PR TITLE
upgrade github provider to 4.4.0

### LINKED ISSUE #34: GitHub provider not supported on arm64 macs (M1)
```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/github v3.0.0 does not have a
│ package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
```

### PR DESCRIPTION
**Pull request by mihaiplesa**
Resolves https://github.com/cloudposse/terraform-github-repository-webhooks/issues/34

### CODE REVIEW

**Review by max-lobur — APPROVED** [review]

**Review by Nuru — CHANGES_REQUESTED** [review]
@osterman @aknysh @nitrocode @max-lobur 
Given the volatility of the `github` provider (relatively frequent breaking changes and even more frequent additional features for authentication options) and the general principle that Terraform modules should be given providers via the root modules and not declare their own, I think the better path here is:
- Remove the `github` provider from `main.tf`
- Change the version pin to `>= 4.2.0` (the first version of the new `integrations/github` source). This would allow M1 users to supply a later version without requiring people to upgrade further than necessary.
- Write migration document (with reference to https://github.com/integrations/terraform-provider-github/issues/652 and https://github.com/integrations/terraform-provider-github/issues/656) to aid users in migrating to this new module. 
- Mark the new release as a breaking change.

For migration strategies, I am thinking:
- Easiest: destroy the current webhooks, upgrade the root module to supply a `github` provider and upgrade to the new version of this module, then create new webhooks.
- Next easiest, and probably works: remove the webhooks from the current Terraform state with `terraform state remove`, upgrade the root module to supply a `github` provider and upgrade to the new version of this module, then import the old webhooks into the new state.
- Harder, and probably no better than the previous technique, follow the guidance in [provider issue #652](https://github.com/integrations/terraform-provider-github/issues/652) to directly migrate the provider and webhook resource.

**Comment by nitrocode** [comment]
I'm a fan of removing the provider. I don't think any of our modules should contain hard coded providers so all of the necessary providers should be passed in.

I like the easiest migration strategy. Seems straight forward and it doesn't sound like it would break anything. If someone was to bump the module without passing in the github provider, the plan should fail, prompting the user to investigate and add the provider.

**Comment by Nuru** [comment]
OK, next step is to test, verify, and document 2 flavors of migration steps (instructions for users who have deployed webhooks with the current module about what to do to upgrade to the new module):
1. Easiest migration path, allowing for a service outage and replacement of old webhooks with new webhooks.
2. Most conservative migration path, with no service outage and preserving existing webhooks.

**Comment by kevcube** [comment]
@Nuru @nitrocode are there cycles available to work on this? this is a dependency for aws-ecs-web-app to run from m1 machines

**Comment by josh-onchain** [comment]
@Nuru @nitrocode  Is this something that can be merged or are there outstanding issues?

**Comment by drselump14** [comment]
> @osterman @aknysh @nitrocode @max-lobur Given the volatility of the `github` provider (relatively frequent breaking changes and even more frequent additional features for authentication options) and the general principle that Terraform modules should be given providers via the root modules and not declare their own, I think the better path here is:
> 
>     * Remove the `github` provider from `main.tf`
> 
>     * Change the version pin to `>= 4.2.0` (the first version of the new `integrations/github` source). This would allow M1 users to supply a later version without requiring people to upgrade further than necessary.
> 

I've made a PR as @Nuru suggested

https://github.com/cloudposse/terraform-github-repository-webhooks/pull/40

**Pull request closed without merging**
