### PR TITLE
docs: typo in usage example

### PR DESCRIPTION
**Pull request by joppa27**

### CODE REVIEW

**Comment by osterman** [comment]
@solairerove can you rebuild this readme? Thanks!

**Comment by osterman** [comment]
Thanks @joppa27 for reporting

**Comment by solairerove** [comment]
https://github.com/joppa27/terraform-github-repository-webhooks/pull/1
@joppa27 
@osterman 
review plz

**Review by solairerove — COMMENTED** [review]
joppa27#1
@joppa27
@osterman
review plz

**Comment by solairerove** [comment]
@osterman done with rebuild
@joppa27 ty)

**Review by osterman — APPROVED** [review]

**Pull request merged**
