### PR TITLE
Terraform 0.14 upgrade

### PR DESCRIPTION
**Pull request by maximmi**
## what
- Upgrade to support Terraform 0.14 and bring up to current Cloud Posse standard

## why
- Support Terraform 0.14

### CODE REVIEW

**Comment by jross-ai** [comment]
Hello, looks like all of the checks have passed and this PR just need a review. Is there an ETA for when we can expect this to be released? Hoping to use this repo with terraform v14. Thanks and really appreciate the work you are doing!

**Review by osterman — APPROVED** [review]

**Pull request merged**
