### PR TITLE
Convert to terraform 0.12

### PR DESCRIPTION
**Pull request by uchiumih**
I fixed a missing conversion of old code to Terraform 0.12.

### CODE REVIEW

**Comment by uchiumih** [comment]
I got this warning before fix.

```
Warning: Quoted references are deprecated

  on .terraform/modules/github_webhooks/main.tf line 24, in resource "github_repository_webhook" "default":
  24:     ignore_changes = ["configuration[0].secret"]

In this context, references are expected literally rather than in quotes.
Terraform 0.11 and earlier required quotes, but quoted references are now
deprecated and will be removed in a future version of Terraform. Remove the
quotes surrounding this reference to silence this warning.
```

**Review by maximmi — CHANGES_REQUESTED** [review]
@uchiumih please, rebase PR

**Comment by maximmi** [comment]
@uchiumih please, rebase PR

**Comment by osterman** [comment]
This has been fixed in #18 

Thanks for opening the PR! We had some tests that needed fixing for me to get this to work

**Pull request closed without merging**
